/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billing.software;

/**
 *
 * @author Rozzi Roti
 */
public class AddProduct extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    public AddProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        backToListButton = new javax.swing.JButton();
        upperborderPannel = new javax.swing.JPanel();
        mastersButton = new javax.swing.JButton();
        salebarButton = new javax.swing.JButton();
        purchasebarButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();
        addCustomerLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        itemLabel = new javax.swing.JLabel();
        unitLabel = new javax.swing.JLabel();
        rateLabel = new javax.swing.JLabel();
        cgstLabel = new javax.swing.JLabel();
        sgstLabel = new javax.swing.JLabel();
        itemTextField = new javax.swing.JTextField();
        unitTextField = new javax.swing.JTextField();
        cgstTextField = new javax.swing.JTextField();
        sgstTextField = new javax.swing.JTextField();
        rateTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        igstTextField = new javax.swing.JTextField();
        igstLabel = new javax.swing.JLabel();
        hsnTextField = new javax.swing.JTextField();
        cgstLabel1 = new javax.swing.JLabel();
        sgstLabel1 = new javax.swing.JLabel();
        reverseLabel = new javax.swing.JLabel();
        reverseChargeTextField = new javax.swing.JTextField();
        categoryComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        percentReverseLabel = new javax.swing.JLabel();
        perReverseChargeTextField = new javax.swing.JTextField();
        cessLabel = new javax.swing.JLabel();
        cessTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 204, 51));

        backToListButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        backToListButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Back_25px_1.png"))); // NOI18N
        backToListButton.setText("Back to List");
        backToListButton.setToolTipText("");
        backToListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToListButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backToListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backToListButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        upperborderPannel.setBackground(new java.awt.Color(255, 204, 51));

        mastersButton.setBackground(new java.awt.Color(51, 255, 102));
        mastersButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        mastersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Support_24px.png"))); // NOI18N
        mastersButton.setText("Masters");

        salebarButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        salebarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Land_Sales_24px.png"))); // NOI18N
        salebarButton.setText("Sales");

        purchasebarButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        purchasebarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Receipt_24px.png"))); // NOI18N
        purchasebarButton.setText("Purchase");

        logoutButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_Export_24px.png"))); // NOI18N
        logoutButton.setText("Logout");

        javax.swing.GroupLayout upperborderPannelLayout = new javax.swing.GroupLayout(upperborderPannel);
        upperborderPannel.setLayout(upperborderPannelLayout);
        upperborderPannelLayout.setHorizontalGroup(
            upperborderPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperborderPannelLayout.createSequentialGroup()
                .addContainerGap(348, Short.MAX_VALUE)
                .addComponent(mastersButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salebarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purchasebarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addContainerGap())
        );
        upperborderPannelLayout.setVerticalGroup(
            upperborderPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upperborderPannelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(upperborderPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton)
                    .addComponent(purchasebarButton)
                    .addComponent(salebarButton)
                    .addComponent(mastersButton))
                .addContainerGap())
        );

        addCustomerLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        addCustomerLabel.setText("Add Product");

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        itemLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        itemLabel.setText("Item");

        unitLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        unitLabel.setText("Unit");

        rateLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        rateLabel.setText("Rate");

        cgstLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        cgstLabel.setText("CGST");

        sgstLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        sgstLabel.setText("SGST");

        saveButton.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        saveButton.setText("Save & Next");

        igstLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        igstLabel.setText("IGST");

        cgstLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        cgstLabel1.setText("HSN/SAC Code");

        sgstLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        sgstLabel1.setText("Category");

        reverseLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        reverseLabel.setText("Reverse Charge");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Service", "Goods" }));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Choose HSN/SAC Code");

        percentReverseLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        percentReverseLabel.setText("% Reverse Charge");

        cessLabel.setFont(new java.awt.Font("Tempus Sans ITC", 0, 16)); // NOI18N
        cessLabel.setText("Cess");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addGap(187, 187, 187))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(unitLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(itemLabel)
                                .addGap(37, 37, 37)
                                .addComponent(itemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(unitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rateLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cgstLabel1)
                            .addComponent(sgstLabel1)
                            .addComponent(reverseLabel)
                            .addComponent(percentReverseLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(hsnTextField)
                                    .addComponent(reverseChargeTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(categoryComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 138, Short.MAX_VALUE)
                                    .addComponent(perReverseChargeTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cgstLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sgstLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(igstLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(cessLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cgstTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(sgstTextField)
                                .addComponent(igstTextField, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemLabel)
                    .addComponent(itemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(unitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rateLabel)
                        .addComponent(rateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(unitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cgstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cgstLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sgstLabel)
                            .addComponent(sgstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(igstLabel)
                            .addComponent(igstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hsnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cgstLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sgstLabel1)
                            .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reverseLabel)
                            .addComponent(reverseChargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cessLabel)
                        .addComponent(cessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(perReverseChargeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(percentReverseLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(upperborderPannel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCustomerLabel))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(upperborderPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCustomerLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToListButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backToListButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addCustomerLabel;
    private javax.swing.JButton backToListButton;
    private javax.swing.JComboBox<String> categoryComboBox;
    private javax.swing.JLabel cessLabel;
    private javax.swing.JTextField cessTextField;
    private javax.swing.JLabel cgstLabel;
    private javax.swing.JLabel cgstLabel1;
    private javax.swing.JTextField cgstTextField;
    private javax.swing.JTextField hsnTextField;
    private javax.swing.JLabel igstLabel;
    private javax.swing.JTextField igstTextField;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JTextField itemTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton mastersButton;
    private javax.swing.JTextField perReverseChargeTextField;
    private javax.swing.JLabel percentReverseLabel;
    private javax.swing.JButton purchasebarButton;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JTextField rateTextField;
    private javax.swing.JTextField reverseChargeTextField;
    private javax.swing.JLabel reverseLabel;
    private javax.swing.JButton salebarButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sgstLabel;
    private javax.swing.JLabel sgstLabel1;
    private javax.swing.JTextField sgstTextField;
    private javax.swing.JLabel unitLabel;
    private javax.swing.JTextField unitTextField;
    private javax.swing.JPanel upperborderPannel;
    // End of variables declaration//GEN-END:variables
}
